# Generated by Django 4.1.5 on 2023-01-31 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
        migrations.AlterModelTable(
            name='person',
            table='content"."person',
        ),
        migrations.AlterModelTable(
            name='personfilmwork',
            table='content"."person_film_work',
        ),
    ]
